package com.s1g1.axiduo.model

import androidx.annotation.StringRes
import com.s1g1.axiduo.R

enum class Question(
    val id: Int,
    @StringRes val sentence: Int,
    val axis: MBTIAxis,
    val axisDirection: Int
)
{
    Question1(
        id=1,
        sentence= R.string.mbti_question_1,
        axis=MBTIAxis.Energy,
        axisDirection=1),
    Question2(
        id=2,
        sentence=R.string.mbti_question_2,
        axis=MBTIAxis.Mind,
        axisDirection=-1),
    Question3(
        id=3,
        sentence=R.string.mbti_question_3,
        axis=MBTIAxis.Nature,
        axisDirection=-1),
    Question4(
        id=4,
        sentence=R.string.mbti_question_4,
        axis=MBTIAxis.Tactics,
        axisDirection=1),
    Question5(
        id=5,
        sentence=R.string.mbti_question_5,
        axis=MBTIAxis.Tactics,
        axisDirection=1),
    Question6(
        id=6,
        sentence=R.string.mbti_question_6,
        axis=MBTIAxis.Energy,
        axisDirection=1),
    Question7(
        id=7,
        sentence=R.string.mbti_question_7,
        axis=MBTIAxis.Tactics,
        axisDirection=1),
    Question8(
        id=8,
        sentence=R.string.mbti_question_8,
        axis=MBTIAxis.Nature,
        axisDirection=-1),
    Question9(
        id=9,
        sentence=R.string.mbti_question_9,
        axis=MBTIAxis.Tactics,
        axisDirection=1),
    Question10(
        id=10,
        sentence=R.string.mbti_question_10,
        axis=MBTIAxis.Tactics,
        axisDirection=-1),
    Question11(
        id=11,
        sentence=R.string.mbti_question_11,
        axis=MBTIAxis.Energy,
        axisDirection=1),
    Question12(
        id=12,
        sentence=R.string.mbti_question_12,
        axis=MBTIAxis.Mind,
        axisDirection=1),
    Question13(
        id=13,
        sentence=R.string.mbti_question_13,
        axis=MBTIAxis.Nature,
        axisDirection=1),
    Question14(
        id=14,
        sentence=R.string.mbti_question_14,
        axis=MBTIAxis.Tactics,
        axisDirection=-1),
    Question15(
        id=15,
        sentence=R.string.mbti_question_15,
        axis=MBTIAxis.Energy,
        axisDirection=-1),

    Question16(
        id=16,
        sentence=R.string.mbti_question_16,
        axis=MBTIAxis.Energy,
        axisDirection=1),
    Question17(
        id=17,
        sentence=R.string.mbti_question_17,
        axis=MBTIAxis.Mind,
        axisDirection=-1),
    Question18(
        id=18,
        sentence=R.string.mbti_question_18,
        axis=MBTIAxis.Nature,
        axisDirection=-1),
    Question19(
        id=19,
        sentence=R.string.mbti_question_19,
        axis=MBTIAxis.Mind,
        axisDirection=-1),
    Question20(
        id=20,
        sentence=R.string.mbti_question_20,
        axis=MBTIAxis.Tactics,
        axisDirection=-1),
    Question21(
        id=21,
        sentence=R.string.mbti_question_21,
        axis=MBTIAxis.Energy,
        axisDirection=-1),
    Question22(
        id=22,
        sentence=R.string.mbti_question_22,
        axis=MBTIAxis.Mind,
        axisDirection=1),
    Question23(
        id=23,
        sentence=R.string.mbti_question_23,
        axis=MBTIAxis.Nature,
        axisDirection=1),
    Question24(
        id=24,
        sentence=R.string.mbti_question_24,
        axis=MBTIAxis.Tactics,
        axisDirection=1),
    Question25(
        id=25,
        sentence=R.string.mbti_question_25,
        axis=MBTIAxis.Nature,
        axisDirection=1),
    Question26(
        id=26,
        sentence=R.string.mbti_question_26,
        axis=MBTIAxis.Energy,
        axisDirection=-1),
    Question27(
        id=27,
        sentence=R.string.mbti_question_27,
        axis=MBTIAxis.Mind,
        axisDirection=-1),
    Question28(
        id=28,
        sentence=R.string.mbti_question_28,
        axis=MBTIAxis.Nature,
        axisDirection=1),
    Question29(
        id=29,
        sentence=R.string.mbti_question_29,
        axis=MBTIAxis.Tactics,
        axisDirection=-1),
    Question30(
        id=30,
        sentence=R.string.mbti_question_30,
        axis=MBTIAxis.Nature,
        axisDirection=1),
    Question31(
        id=31,
        sentence=R.string.mbti_question_31,
        axis=MBTIAxis.Energy,
        axisDirection=1),
    Question32(
        id=32,
        sentence=R.string.mbti_question_32,
        axis=MBTIAxis.Nature,
        axisDirection=-1),
    Question33(
        id=33,
        sentence=R.string.mbti_question_33,
        axis=MBTIAxis.Nature,
        axisDirection=-1),
    Question34(
        id=34,
        sentence=R.string.mbti_question_34,
        axis=MBTIAxis.Tactics,
        axisDirection=-1),
    Question35(
        id=35,
        sentence=R.string.mbti_question_35,
        axis=MBTIAxis.Tactics,
        axisDirection=1),
    Question36(
        id=36,
        sentence=R.string.mbti_question_36,
        axis=MBTIAxis.Energy,
        axisDirection=1),
    Question37(
        id=37,
        sentence=R.string.mbti_question_37,
        axis=MBTIAxis.Mind,
        axisDirection=-1),
    Question38(
        id=38,
        sentence=R.string.mbti_question_38,
        axis=MBTIAxis.Nature,
        axisDirection=1),

    Question39(
        id=39,
        sentence=R.string.mbti_question_39,
        axis=MBTIAxis.Tactics,
        axisDirection=1),
    Question40(
        id=40,
        sentence=R.string.mbti_question_40,
        axis=MBTIAxis.Tactics,
        axisDirection=1),
    Question41(
        id=41,
        sentence=R.string.mbti_question_41,
        axis=MBTIAxis.Energy,
        axisDirection=-1),
    Question42(
        id=42,
        sentence=R.string.mbti_question_42,
        axis=MBTIAxis.Nature,
        axisDirection=-1),
    Question43(
        id=43,
        sentence=R.string.mbti_question_43,
        axis=MBTIAxis.Energy,
        axisDirection=1),
    Question44(
        id=44,
        sentence=R.string.mbti_question_44,
        axis=MBTIAxis.Tactics,
        axisDirection=1),
    Question45(
        id=45,
        sentence=R.string.mbti_question_45,
        axis=MBTIAxis.Tactics,
        axisDirection=-1),
    Question46(
        id=46,
        sentence=R.string.mbti_question_46,
        axis=MBTIAxis.Mind,
        axisDirection=1),
    Question47(
        id=47,
        sentence=R.string.mbti_question_47,
        axis=MBTIAxis.Nature,
        axisDirection=-1),
    Question48(
        id=48,
        sentence=R.string.mbti_question_48,
        axis=MBTIAxis.Nature,
        axisDirection=-1),
    Question49(
        id=49,
        sentence=R.string.mbti_question_49,
        axis=MBTIAxis.Tactics,
        axisDirection=-1),
    Question50(
        id=50,
        sentence=R.string.mbti_question_50,
        axis=MBTIAxis.Tactics,
        axisDirection=-1),
    Question51(
        id=51,
        sentence=R.string.mbti_question_51,
        axis=MBTIAxis.Energy,
        axisDirection=-1),
    Question52(
        id=52,
        sentence=R.string.mbti_question_52,
        axis=MBTIAxis.Mind,
        axisDirection=1),
    Question53(
        id=53,
        sentence=R.string.mbti_question_53,
        axis=MBTIAxis.Energy,
        axisDirection=1),
    Question54(
        id=54,
        sentence=R.string.mbti_question_54,
        axis=MBTIAxis.Mind,
        axisDirection=-1),
    Question55(
        id=55,
        sentence=R.string.mbti_question_55,
        axis=MBTIAxis.Tactics,
        axisDirection=-1),
    Question56(
        id=56,
        sentence=R.string.mbti_question_56,
        axis=MBTIAxis.Tactics,
        axisDirection=1),
    Question57(
        id=57,
        sentence=R.string.mbti_question_57,
        axis=MBTIAxis.Mind,
        axisDirection=-1),
    Question58(
        id=58,
        sentence=R.string.mbti_question_58,
        axis=MBTIAxis.Nature,
        axisDirection=-1),
    Question59(
        id=59,
        sentence=R.string.mbti_question_59,
        axis=MBTIAxis.Tactics,
        axisDirection=-1),
    Question60(
        id=60,
        sentence=R.string.mbti_question_60,
        axis=MBTIAxis.Tactics,
        axisDirection=1),

}